企業ロゴの画像サイズの変更
amatech-repo/amatech-web-site pull request #16
Opened 2023-06-07 01:19 UTC by maple-fm

## このプルリクエストの目的
企業ロゴのサイズが異なることが原因でコンポーネントが上手く実装できなかったため

## 変更の内容
- [x] svg形式の企業ロゴ画像サイズを1:1にして再度public/logoに保存した
- [x]

## その他

2023-06-07 01:30 UTC, kazuito reviewed
画像のアスペクト比の問題はCSSで解決できると思います。
あと、企業ロゴは全てPNGファイルなので.pngで書き出しして頂きたいです！

2023-06-07 02:20 UTC, maple-fm commented
> 画像のアスペクト比の問題はCSSで解決できると思います。 ~あと、企業ロゴは全てPNGファイルなので.pngで書き出しして頂きたいです！~ あと、企業ロゴはSVGファイルではないので.pngか.jpgで書き出して頂きたいです！

画像のためだけにcssファイル作るのも面倒かなと
企業ロゴの形式に関しては、FigmaからSVGファイルでエキスポートできる機能があるので全部それで変換してます(他の画像も)

| 出力比較 | コード比較  |
| --- | --- |
| <img width="673" alt="スクリーンショット 2023-06-07 11 12 31" src="https://github.com/amatech-repo/amatech-web-site/assets/104209788/14320369-f557-4d89-905f-69d3a094dda6"> |  ![スクリーンショット 2023-06-07 11 12 38](https://github.com/amatech-repo/amatech-web-site/assets/104209788/f9ca2499-9956-4b6b-bb46-ea7e8d34c223) | 


この比較見る感じsvg形式の方が画質が良くなるんだけど、pngの方がいいかな？

2023-06-07 05:24 UTC, yk-mt12 commented
あまり今回の差分に変更はないけど、企業ロゴは、microCMSから取得することになりそうだね。

画像のパス自体は、ローカルのパスじゃなくて、microCMSから取得した時のURLに変更することになりそう！
サイズ自体は、アップロードした時の画像になるので、そのままローカルに保存しておいて大丈夫だと思います！

2023-06-07 05:25 UTC, yk-mt12 commented
画像は、SVGかwebpで取りたいです。
pngだと画像の解像度が変化するのだけど、SVG, webpは画像の解像度が変化しないので、基本的にSVGでやりたいですね〜！

@maple-fm @kazuito

2023-06-08 18:30 UTC, yk-mt12 requested changes
tech trainのロゴがheight, width:159pxだと思うんだけど、159pxって切り悪いから、160pxにしてほしいかも？

Imageタグが多分アスペクト比の固定だったはずだけど、倍率変えた時に計算が少し面倒になる可能性もあるし！（あるかわからないが。。）

2023-06-11 04:34 UTC, yk-mt12 requested changes

2023-06-11 04:34 UTC, yk-mt12 commented on public/logo/amatech.svg
これ、なんかアイコンかけてるw
ブランチ入ってみたけど、そっちでもかけてそう！

<img width="613" alt="スクリーンショット 2023-06-11 13 34 09" src="https://github.com/amatech-repo/amatech-web-site/assets/67742985/99206b82-9326-40a5-98b0-8199e2c1017b">

2023-06-11 04:52 UTC, maple-fm commented on public/logo/amatech.svg
コードから直接編集するの良くないかもな

2023-06-21 01:47 UTC, maple-fm commented
@yk-mt12 
企業ロゴとかcmsから渡すなら、このPRもう必要ないよね

2023-06-26 13:34 UTC, closed without merging